version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: business_insights_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password2026
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: business_insights_queue
    ports:
      - "5672:5672"   # Puerto de mensajería (AMQP)
      - "15672:15672" # Puerto del Panel de Control Web
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guestdocker compose up -d

volumes:
  mssql_data: